version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "automerge"
    # Allow up to 10 open pull requests at a time
    open-pull-requests-limit: 10
    # Create pull requests for version updates
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
    # Specify which dependencies to update
    allow:
      # Allow updates for all dependencies
      - dependency-type: "all"
    # Add reviewers
    reviewers:
      - "owner"
    # Group dependencies together
    groups:
      # Group production dependencies together
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
      # Group development dependencies together
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "automerge"
